[

  // Greek letters
  {trigger: "@a", replacement: "\\alpha", options: "mA"},
  {trigger: "@b", replacement: "\\beta", options: "mA"},
  {trigger: "@g", replacement: "\\gamma", options: "mA"},
  {trigger: "@G", replacement: "\\Gamma", options: "mA"},
  {trigger: "@d", replacement: "\\delta", options: "mA"},
  {trigger: "@D", replacement: "\\Delta", options: "mA"},
  {trigger: "@e", replacement: "\\epsilon", options: "mA"},
  {trigger: ":e", replacement: "\\varepsilon", options: "mA"},
  {trigger: "@z", replacement: "\\zeta", options: "mA"},
  {trigger: "@t", replacement: "\\theta", options: "mA"},
  {trigger: "@T", replacement: "\\Theta", options: "mA"},
  {trigger: ":t", replacement: "\\vartheta", options: "mA"},
  {trigger: "@i", replacement: "\\iota", options: "mA"},
  {trigger: "@k", replacement: "\\kappa", options: "mA"},
  {trigger: "@l", replacement: "\\lambda", options: "mA"},
  {trigger: "@L", replacement: "\\Lambda", options: "mA"},
  {trigger: "@s", replacement: "\\sigma", options: "mA"},
  {trigger: "@S", replacement: "\\Sigma", options: "mA"},
  {trigger: "@u", replacement: "\\upsilon", options: "mA"},
  {trigger: "@U", replacement: "\\Upsilon", options: "mA"},
  {trigger: "@o", replacement: "\\omega", options: "mA"},
  {trigger: "@O", replacement: "\\Omega", options: "mA"},
  {trigger: "ome", replacement: "\\omega", options: "mA"},
  {trigger: "Ome", replacement: "\\Omega", options: "mA"},


  // some grek letters can just be typed for convienence
  {trigger: "([^\\\\])(${GREEK})", replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before Greek letters"},
  {trigger: "([^\\\\])(${SYMBOL})", replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before symbols"},

  // Insert space after Greek letters and symbols
  {trigger: "\\\\(${GREEK}|${SYMBOL}|${MORE_SYMBOLS})([A-Za-z])", replacement: "\\[[0]] [[1]]", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) sr", replacement: "\\[[0]]^{2}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) cb", replacement: "\\[[0]]^{3}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) rd", replacement: "\\[[0]]^{$0}$1", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) hat", replacement: "\\hat{\\[[0]]}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) dot", replacement: "\\dot{\\[[0]]}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) bar", replacement: "\\bar{\\[[0]]}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) vec", replacement: "\\vec{\\[[0]]}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) tilde", replacement: "\\tilde{\\[[0]]}", options: "rmA"},
  {trigger: "\\\\(${GREEK}|${SYMBOL}) und", replacement: "\\underline{\\[[0]]}", options: "rmA"},

  // Here we do it for text mode aswell
  {trigger: "@a", replacement: "$\\alpha$ ", options: "t"},
  {trigger: "@b", replacement: "$\\beta$ ", options: "t"},
  {trigger: "@g", replacement: "$\\gamma$ ", options: "t"},
  {trigger: "@G", replacement: "$\\Gamma$ ", options: "t"},
  {trigger: "@d", replacement: "$\\delta$ ", options: "t"},
  {trigger: "@D", replacement: "$\\Delta$ ", options: "t"},
  {trigger: "@e", replacement: "$\\epsilon$ ", options: "t"},
  {trigger: ":e", replacement: "$\\varepsilon$ ", options: "t"},
  {trigger: "@z", replacement: "$\\zeta$ ", options: "t"},
  {trigger: "@t", replacement: "$\\theta$ ", options: "t"},
  {trigger: "@T", replacement: "$\\Theta$ ", options: "t"},
  {trigger: ":t", replacement: "$\\vartheta$ ", options: "t"},
  {trigger: "@i", replacement: "$\\iota$ ", options: "t"},
  {trigger: "@k", replacement: "$\\kappa$ ", options: "t"},
  {trigger: "@l", replacement: "$\\lambda$ ", options: "t"},
  {trigger: "@L", replacement: "$\\Lambda$ ", options: "t"},
  {trigger: "@s", replacement: "$\\sigma$ ", options: "t"},
  {trigger: "@S", replacement: "$\\Sigma$ ", options: "t"},
  {trigger: "@u", replacement: "$\\upsilon$ ", options: "t"},
  {trigger: "@U", replacement: "$\\Upsilon$ ", options: "t"},
  {trigger: "@o", replacement: "$\\omega$ ", options: "t"},
  {trigger: "@O", replacement: "$\\Omega$ ", options: "t"},
  {trigger: "ome", replacement: "$\\omega$ ", options: "t"},
  {trigger: "Ome", replacement: "$\\Omega$ ", options: "t"},
]
